### ISSUE TITLE
Set the Client.user to null inside Client.js as it should be nullable.

### ISSUE THREAD

**Issue by ghost** [discord-jcord/jcord#2]
@KevvyCodes thanks.

**Comment by KevvyCodes** [comment]
`Client#user` is only received once the ready event is emitted. But sure i'll add it

**Comment by ghost** [comment]
> `Client#user` is only received once the ready event is emitted. But sure i'll add it

I've seen that but if the websocket hasn't send the ClientUser if would error out, it instead should return null.
